### ISSUE TITLE
Link to the official Salt Sensu-formula instead?

### ISSUE THREAD

**Issue by solarkennedy** [sensu/sensu-salt#1]
This repo is not maintained, and the code listed isn't really in a reusable state. (see: https://github.com/sensu/sensu-salt/blob/master/sensu/server-config.json)

How about linking to the official salt formula instead?
https://github.com/saltstack-formulas/sensu-formula

It is much more flexible and up to date. Additionally it only manages Sensu and doesn't manipulate rabbitmq/redis/git.

**Comment by russellballestrini** [comment]
I maintain this repo.  I have not changed it since writing it, but I can assure you that I will fix issues people have.

**Comment by solarkennedy** [comment]
Ok. I'll go ahead and close the issue then, but I'll continue to use the official formula.
