### ISSUE TITLE
Best direction for SaltStack Formulas and clarifying Maintainers

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-salt#2]
It looks like this is no longer being maintained and people are using: https://github.com/powellchristoph/sensu-formula or more recently https://github.com/saltstack-formulas/sensu-formula we should add a deprecation notice and point to it or invest in cleaning this up. I am more than happy to add the deprecation notice and links but I wanted to check if we wanted to bring that back alive again before starting any changes.

**Comment by russellballestrini** [comment]
I'm fine with whatever.  Just an FYI I'm fairly certain all these states still work.

**Comment by mbbroberg** [comment]
The repo hasn't been updated, but it also doesn't have any open issues. So it might just be good 😄 

I'd be curious to know whether, in general, we should recommend @powellchristoph's work in https://github.com/saltstack-formulas/sensu-formula. I don't know enough about the salt community to know if you're only using things under the `saltstack-formulas` org (like we do with `sensu-plugins`). Is that true? 

No matter the conclusion, so much ❤️ to you @russellballestrini for making this in the first place.

**Comment by perlchild** [comment]
It's my understanding (I'm new to sensu, less new to salt) that newcomers are invited to look at the salt-formulas organisation first.  That doesn't mean anything outside of that is bad, but the org tries to keep style/conventions more consistent.

**Comment by majormoses** [comment]
Correct, I am just pointing out that this repo has not had a contribution since 2013 while the other is currently maintained. I am not saying we should yank the code (not saying that's off the table) just saying maybe we should link to it so that anyone looking for a more up to date formula.

**Comment by mbbroberg** [comment]
Hey all! We're to a point with the maintainers program where I'd like to invite those with time to participate in it! Official request: https://github.com/sensu-plugins/community/issues/79

Specifically, I'd love someone more experienced than me deciding on how to make the repo under the Sensu organization the best resource for the SaltStack community, whether that means updating this, pointing here: https://github.com/saltstack-formulas/sensu-formula or doing something totally different. 

No matter the conclusion, I can't say enough how impressive everyone's work has been on this effort! We're focused on making the right move forward.

**Comment by russellballestrini** [comment]
I can help out if needed but it seems like you all might have other people who would like to maintain or switch to the salt formula repo as the source.

Please feel free to archive this version that I created so that it is still accessible to the internal sensu team and reduce confusion for the community.

I don't use sensu at the moment so I think it would be more appropriate if somebody more motivated takes the reins.

I'm busy working full time at remind.com and moonlighting on https://www.remarkbox.com during nights.  When Remarkbox grows a bit bigger I fully plan to stand up sensu for monitoring. ; )

**Comment by mbbroberg** [comment]
We're onboarding awesome new maintainers that will be listed in my next PR to here: https://github.com/sensu-plugins/community#maintained-areas

So much ❤️to all of you!
