### ISSUE TITLE
update repository

### ISSUE THREAD

**Issue by x70b1** [sensu/sensu-salt#6]
To improve this repo, I would suggest:

- [x] Change the Topic to something like: `Your source to use Sensu with SaltStack.`
- [x] Hide the wiki (I would write useful information in the README.md so that it is on the first page and can be seen quickly)
- [x] Close issues #2 because it should no longer be needed

**Comment by mbbroberg** [comment]
Done! Also removed the external link for the website. Great call @x70b1.
